routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Webview
Route::group(['namespace' => 'Webview', 'prefix' => 'webview', 'as' => 'webview.'], function() {
	Route::get('password/reset/{token}', 'ResetPasswordController@resetPage')->name('reset.password.page');
	Route::post('password/reset', 'ResetPasswordController@reset')->name('reset.password');

	Route::get('terms-conditions', 'AboutAppController@termsConditions')->name('terms-conditions');
	Route::get('privacy-policy', 'AboutAppController@privacyPolicy')->name('privacy-policy');
	Route::get('about-us', 'AboutAppController@aboutUs')->name('about-us');
	Route::get('package-info', 'AboutAppController@packageInfo')->name('package-info');

	Route::get('/promo/{promo}', 'PromoController@detail')->name('promo-detail');
	Route::get('cara-isi-saldo', function() {
		return view('webview.cara-isi-saldo');
	});

	// Logged in
	Route::group(['middleware' => 'auth.params'], function() {
		Route::get('binary', 'BinaryController@show')->name('binary');
	});
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Guest
	Route::group(['middleware' => 'guest:web-admin', 'guard' => 'web-admin'], function() {
		Route::get('login', 'AuthController@loginPage')->name('login.page');
		Route::post('login', 'AuthController@login')->name('login');
	});

	// Logged In
	Route::group(['middleware' => 'auth:web-admin', 'guard' => 'web-admin'], function() {
	    Route::post('logout', 'AuthController@logout')->name('logout');
		Route::get('', 'DashboardController@index')->name('dashboard');
		
		// Admin
		Route::group(['prefix' => 'admins', 'as' => 'admins.'], function() {
			Route::get('/', 'AdminController@index')->name('index');
			Route::post('/', 'AdminController@ajax')->name('ajax');
			
			Route::get('/new', 'AdminController@edit')->name('create');
			Route::get('/{admin}/edit', 'AdminController@edit')->name('edit');
			Route::post('/store', 'AdminController@update')->name('store');
			Route::post('/{admin}/update', 'AdminController@update')->name('update');
			Route::delete('/{admin}/delete', 'AdminController@delete')->name('delete');
		});
		// User
		Route::group(['namespace' => 'User', 'prefix' => 'users', 'as' => 'users.'], function() {
			// User List
			Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
				Route::get('/', 'UserController@index')->name('index');
				Route::post('/', 'UserController@ajax')->name('ajax');
				Route::get('/{user}/detail', 'UserController@detail')->name('detail');
				Route::get('/new', 'UserController@edit')->name('create');
				Route::get('/{user}/edit', 'UserController@edit')->name('edit');
				Route::post('/store', 'UserController@update')->name('store');
				Route::post('/{user}/update', 'UserController@update')->name('update');
				Route::delete('/{user}/delete', 'UserController@delete')->name('delete');
			});
			// User upgrade request
			Route::group(['prefix' => 'upgrade-request', 'as' => 'upgrade-request.'], function() {
				Route::get('/', 'UpgradeRequestController@index')->name('index');
				Route::post('/', 'UpgradeRequestController@ajax')->name('ajax');
				
				Route::get('/{upgradeRequest}/edit', 'UpgradeRequestController@edit')->name('edit');
				Route::post('/{upgradeRequest}/approve', 'UpgradeRequestController@approve')->name('approve');
				Route::post('/{upgradeRequest}/decline', 'UpgradeRequestController@decline')->name('decline');
				Route::delete('/{upgradeRequest}/delete', 'UpgradeRequestController@delete')->name('delete');
			});
			// User verify identity
			Route::group(['prefix' => 'verify-identity', 'as' => 'verify-identity.'], function() {
				Route::get('/', 'VerifyIdentityController@index')->name('index');
				Route::post('/', 'VerifyIdentityController@ajax')->name('ajax');
				
				Route::get('/{user}/edit', 'VerifyIdentityController@edit')->name('edit');
				Route::post('/{user}/approve', 'VerifyIdentityController@approve')->name('approve');
				Route::post('/{user}/decline', 'VerifyIdentityController@decline')->name('decline');
				Route::delete('/{user}/delete', 'VerifyIdentityController@delete')->name('delete');
			});
			// Route::group(['prefix' => 'pair', 'as' => 'pair.'], function() {
			// 	Route::get('/', 'PairController@index')->name('index');
			// 	Route::post('/', 'PairController@ajax')->name('ajax');
				
			// 	Route::post('/store', 'PairController@update')->name('store');
			// 	Route::post('/{pair}/claim', 'PairController@claim')->name('claim');
			// 	Route::delete('/{pair}/delete', 'PairController@delete')->name('delete');
			// });
		});
		// Bank
		Route::group(['prefix' => 'bank', 'as' => 'bank.'], function() {
			Route::get('/', 'BankController@index')->name('index');
			Route::post('/', 'BankController@ajax')->name('ajax');
			Route::get('/new', 'BankController@edit')->name('create');
			Route::get('/{bank}/edit', 'BankController@edit')->name('edit');
			Route::post('/store', 'BankController@update')->name('store');
			Route::post('/{bank}/update', 'BankController@update')->name('update');
			Route::delete('/{bank}/delete', 'BankController@delete')->name('delete');
		});
		// Bank Account
		Route::group(['prefix' => 'bank-account', 'as' => 'bank-account.'], function() {
			Route::get('/', 'BankAccountController@index')->name('index');
			Route::post('/', 'BankAccountController@ajax')->name('ajax');
			Route::get('/new', 'BankAccountController@edit')->name('create');
			Route::get('/{bankAccount}/edit', 'BankAccountController@edit')->name('edit');
			Route::post('/store', 'BankAccountController@update')->name('store');
			Route::post('/{bankAccount}/update', 'BankAccountController@update')->name('update');
			Route::delete('/{bankAccount}/delete', 'BankAccountController@delete')->name('delete');
		});
		// Promo
		Route::group(['namespace' => 'Promo', 'prefix' => 'promos', 'as' => 'promos.'], function() {
			// Voucher
			// Route::group(['prefix' => 'voucher', 'as' => 'voucher.'], function(){
			// 	Route::get('/', 'VoucherController@index')->name('index');
			// 	Route::get('/new', 'VoucherController@edit')->name('create');
			// 	Route::get('/{promo}/push-notif', 'VoucherController@pushNotif')->name('push-notif');
			// 	Route::get('/{promo}/authorize', 'VoucherController@authorizeVoucher')->name('authorize');
			// 	Route::get('/{promo}/deauthorize', 'VoucherController@deauthorizeVoucher')->name('deauthorize');
			// 	Route::post('/store', 'VoucherController@update')->name('store');
			// 	Route::get('/{promo}/edit', 'VoucherController@edit')->name('edit');
			// 	Route::post('/{promo}/save', 'VoucherController@update')->name('update');
			// 	Route::post('/{promo}/push-notif', 'VoucherController@postPushNotif')->name('post-push-notif');
			// 	Route::post('/list', 'VoucherController@ajax')->name('ajax');
			// 	Route::delete('/{promo}/delete', 'VoucherController@delete')->name('delete');
			// });
			// Banner
			Route::group(['prefix' => 'banner', 'as' => 'banner.'], function(){
				Route::get('/', 'BannerController@index')->name('index');
				Route::get('/new', 'BannerController@edit')->name('create');
				Route::post('/store', 'BannerController@update')->name('store');
				// Route::get('/{promo}/push-notif', 'BannerController@pushNotif')->name('push-notif');
				Route::get('/{promo}/edit', 'BannerController@edit')->name('edit');
				Route::post('/{promo}/save', 'BannerController@update')->name('update');
				// Route::post('/{promo}/push-notif', 'BannerController@postPushNotif')->name('post-push-notif');
				Route::post('/list', 'BannerController@ajax')->name('ajax');
				Route::delete('/{promo}/delete', 'BannerController@deletePromo')->name('delete');
			});
		});
		// Categories
		Route::group(['prefix' => 'categories', 'as' => 'categories.'], function() {
			Route::get('/', 'CategoryController@index')->name('index');
			Route::post('/', 'CategoryController@ajax')->name('ajax');
			Route::get('/new', 'CategoryController@edit')->name('create');
			Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
			Route::post('/store', 'CategoryController@update')->name('store');
			Route::post('/{category}/update', 'CategoryController@update')->name('update');
			Route::delete('/{category}/delete', 'CategoryController@delete')->name('delete');
		});
		// Products
		Route::group(['prefix' => 'products', 'as' => 'products.'], function() {
			Route::get('/', 'ProductController@index')->name('index');
			Route::post('/', 'ProductController@ajax')->name('ajax');
			Route::get('/new', 'ProductController@edit')->name('create');
			Route::get('/{product}/edit', 'ProductController@edit')->name('edit');
			Route::post('/store', 'ProductController@update')->name('store');
			Route::post('/{product}/update', 'ProductController@update')->name('update');
			Route::delete('/{product}/delete', 'ProductController@delete')->name('delete');
		});
		// Payment
		Route::group(['prefix' => 'payments', 'as' => 'payments.'], function() {
			Route::get('/', 'PaymentController@index')->name('index');
			Route::post('/', 'PaymentController@ajax')->name('ajax');
			Route::get('/external', 'PaymentController@external')->name('external');
			Route::post('/external', 'PaymentController@externalAjax')->name('external-ajax');
			Route::get('/new', 'PaymentController@edit')->name('create');
			Route::get('/{payment}/edit', 'PaymentController@edit')->name('edit');
			Route::post('/store', 'PaymentController@update')->name('store');
			Route::post('/{payment}/update', 'PaymentController@update')->name('update');

app/Http/Controllers/Admin/Promo/BannerController.php
<?php

namespace App\Http\Controllers\Admin\Promo;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB;
use Exception;
use App\Models\Promo;
use App\Enums\ActiveStatus;
use App\Enums\PromoCategory;
use Carbon\Carbon;
use App\Helpers\Managers\PromoManager;
use Validator;
use Yajra\Datatables\Datatables;

class BannerController extends Controller
{
    public function index(Request $request) 
    {
        $statusList = ActiveStatus::getArray();
        return view('admin.promos.banner.index')
            ->with('statusList', $statusList);
    }

    public function ajax(Request $request) 
    {
        $data = Promo::query();
        return Datatables::of($data)
            ->filter(function($query) use ($request) {
                if ($request->has('status_enum') && $request->status_enum !== null) {
                    $query->where('status', $request->status_enum);
                }
            }, true)
            ->addColumn('cover', function ($model) {
                $str = $model->cover_url;
                return $str;
            })
            ->addColumn('start_end_date', function ($model) {
                $str = $model->start_date->format('j F Y').' / '.$model->end_date->format('j F Y');
                return $str;
            })
            ->addColumn('action', function ($model) {
                $str = '<div class="btn-group btn-group-circle">';
                $str .= '<a href='. route('admin.promos.banner.edit', ['promo' => $model->id]) .' class="action"><span class="far fa-edit"></span></a>';
                $str .= '<a data-url="'. route('admin.promos.banner.delete', ['promo' => $model->id]) .'" class="action" data-toggle="modal" data-target="#modalConfirm" data-table-name="#table"><span class="far fa-trash-alt"></span></a>';
                $str .= '</div>';
                return $str;
            })
            ->editColumn('category', function($model) {
                return PromoCategory::getString($model->category);
            })
            ->editColumn('status', function($model) {
                return ActiveStatus::getString($model->status);
            })
            ->make(true);
    }

    public function edit(Request $request, Promo $promo) 
    {
        // $ownerList = Business::pluck('name', 'id');
        $statusList = ActiveStatus::getArray();
        $promoCategories = PromoCategory::getArray();
        // $today = Carbon::now();

        // $livePromos = Promo::where([
        //     ['start_date', '<=', $today],
        //     ['end_date', '>=', $today],
        //     ['status', ActiveStatus::ACTIVE],
        // ])->orderBy('urut', 'desc')->get();

        // $incomingPromos = Promo::where([
        //     ['start_date', '>', $today],
        //     ['status', ActiveStatus::ACTIVE],
        // ])->orderBy('urut', 'desc')->get();
        
        return view('admin.promos.banner.form')
            // ->with('today', $today)
            // ->with('livePromos', $livePromos)
            // ->with('incomingPromos', $incomingPromos)
            ->with('promo', $promo)
            // ->with('ownerList', $ownerList)
            ->with('promoCategories', $promoCategories)
            ->with('statusList', $statusList);
    }

    public function update(Request $request, Promo $promo) 
    {
        $messageType = $promo->id ? 'updated' : 'created';

        $rules = [
            'title' => 'required',
            'category' => 'required',
            'status' => 'required|integer',
            'start_date' => 'required|date',
            'end_date' => 'required|date',
            'description' => 'nullable',
            'tnc' => 'nullable',
            'cover' => 'file',
        ];
        $validator = Validator::make($request->all(), $rules);
        $validator->sometimes('cover', 'required', function($data) use ($promo) {
            return !$promo->id;
        });
        $validator->validate();

        try {
            DB::beginTransaction();
            $promoManager = new PromoManager($request->user());
            // if (!$promo->id) {
            //     $promo = $promoManager->generateUrut($promo, $request->urut);
            // }
            $updatedPromo = $promoManager->update($promo, $request->all());

            DB::commit();
            return redirect()->route('admin.promos.banner.index')->with('success', 'Promo successfully '.$messageType);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return redirect()->back()->with('error', $errorMessage)->withInputs();
        }
    }

    public function deletePromo(Request $request, Promo $promo) {
        try {
            DB::beginTransaction();
            $promoManager = new PromoManager($request->user());
            $updatedPromo = $promoManager->delete($promo);
            DB::commit();
            return response()->json(['message' => 'Promo Deleted'], 200);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return response()->json(['message' => $errorMessage], 500);
        }
    }

    public function pushNotif(Request $request, Promo $promo)
    {
        return view('backend.promos.banner.push-notif')
            ->with('promo', $promo);
    }

    public function postPushNotif(Request $request, Promo $promo)
    {
        $data = [
            'title' => $request->title,
            'message' => $request->message
        ];
        SendNotifications::dispatch($data);
        return redirect()->route('admin.promos.banner.index')->with('success', 'Notification Sent');

    }
}

app/Http/Controllers/Webview/PromoController.php
<?php

namespace App\Http\Controllers\Webview;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Promo;

class PromoController extends Controller
{

    public function detail(Request $request, Promo $promo)
    {
        return view('webview.promo.detail')
            ->with('promo', $promo);
    }
}

resources/views/admin/promos/banner/form.blade.php
@extends('templates.admin.master')

@section('title')
    {{ $promo->id ? 'Edit' : 'Create' }} Banner @parent
@endsection

@section('groupName', 'Promos')

@section('content')
@if (!$promo->id)
{!! Form::open(['route' => 'admin.promos.banner.store', 'method' => 'post', 'files' => true, 'class' => 'form-horizontal']) !!}
@else
{!! Form::model($promo, ['route' => ['admin.promos.banner.update', $promo], 'method' => 'post', 'files' => true, 'class' => 'form-horizontal']) !!}
@endif
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">{{ $promo->id ? 'Edit' : 'Create' }} Banner</h4>
        </div>
        <div class="card-body">
            <div class="row">
                <label for="title" class="col-2 col-form-label">Title</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('title', old('title'), ['class' => 'form-control', 'id' => 'title', 'placeholder' => 'Title']) }}
                        @if($errors->has('title'))
                        <p class="status-text">{{ $errors->first('title') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="desc" class="col-2 col-form-label">Description<br><small>(Optional)</small></label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::textarea('description', old('description'), array('class' => 'form-control d-none', 'id' => 'desc', 'placeholder' => 'Banner Description (Optional)')) }}
                        @if($errors->has('description'))
                        <p class="status-text">{{ $errors->first('description') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="tnc" class="col-2 col-form-label">Terms & Conditions<br><small>(Optional)</small></label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::textarea('tnc', old('tnc'), array('class' => 'form-control d-none', 'id' => 'tnc', 'placeholder' => 'Terms & Conditions (Optional)')) }}
                        @if($errors->has('tnc'))
                        <p class="status-text">{{ $errors->first('tnc') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="category" class="col-2 col-form-label">Banner Category</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::select('category', $promoCategories, old('category'), array('class' => 'form-control', 'id' => 'category', 'placeholder' => 'Select Banner Category')) }}
                        @if($errors->has('category'))
                        <p class="category-text">{{ $errors->first('category') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="status" class="col-2 col-form-label">Status</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::select('status', $statusList, old('status'), array('class' => 'form-control', 'id' => 'status', 'placeholder' => 'Select Status')) }}
                        @if($errors->has('status'))
                        <p class="status-text">{{ $errors->first('status') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="startDate" class="col-2 col-form-label">Start Date</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('start_date', old('start_date'), array('class' => 'form-control datepickers', 'id' => 'startDate', 'placeholder' => 'Start Date')) }}
                        @if($errors->has('start_date'))
                        <p class="status-text">{{ $errors->first('start_date') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="endDate" class="col-2 col-form-label">End Date</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('end_date', old('end_date'), array('class' => 'form-control datepickers', 'id' => 'endDate', 'placeholder' => 'End Date')) }}
                        @if($errors->has('end_date'))
                        <p class="status-text">{{ $errors->first('end_date') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-2 col-form-label">Cover</label>
                <div class="col-10">
                    <div class="form-group">
                        <div class="fileinput text-center fileinput-new d-inline-block" data-provides="fileinput">
                            <div class="fileinput-new thumbnail">
                                <img src="{{ $promo->id && $promo->cover_url ? $promo->cover_url : asset('/images/img-placeholder.png') }}">
                            </div>
                            <div class="fileinput-preview fileinput-exists thumbnail" style=""></div>
                            <div>
                                <span class="btn btn-primary btn-round btn-file">
                                    <span class="fileinput-new">Select image</span>
                                    <span class="fileinput-exists"><i class="fas fa-pencil-alt"></i> Change</span>
                                    {{ Form::file('cover') }}
                                </span>
                                <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fas fa-times-circle"></i> Remove</a>
                            </div>
                        </div>
                        @if($errors->has('cover'))
                        <p class="status-text">{{ $errors->first('cover') }}</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="text-center">
                <button type="submit" class="btn btn-round btn-info"><i class="fas fa-paper-plane"></i> Submit</button>
            </div>
        </div>
    </div>
{!! Form::close() !!}
@endsection

@push('pageRelatedCss')
<link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap-datepicker.min.css') }}">
@endpush

@push('pageRelatedJs')
<script src="{{ asset('/js/jasny-bootstrap.min.js') }}"></script>
<script src="{{ asset('/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('/ckeditor/ckeditor.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
    var inputStart = $('input[name="start_date"]');
    var inputEnd = $('input[name="end_date"]');

    inputStart.datepicker({
        format: 'yyyy-mm-dd',
        autoclose: true,
        startDate: new Date(),
        todayHighlight: true
    });

    inputStart.on('change', function() {
        let val = inputStart.datepicker('getDates');
        let endVal = new Date(inputEnd.val());
        // let endVal = inputEnd.datepicker('getDates');

        if (val.length != 0) {
            if (endVal.length != 0 && val[0] > endVal) {
                inputEnd.val('');
            }

            inputEnd.datepicker('destroy');
            inputEnd.datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayHighlight: true,
                startDate: val[0]
            });

            inputEnd.prop('disabled', false);
        } else {
            inputEnd.prop('disabled', true);
        }
    });

    CKEDITOR.replace('description', {
        height: 300
    });

    CKEDITOR.replace('tnc', {
        height: 300
    });

});
</script>
@endpush

resources/views/admin/promos/banner/index.blade.php
@extends('templates.admin.master')
@extends('templates.datatables.datatables')

@section('title')
    Promo Banner @parent
@endsection

@section('groupName', 'Promos')

@section('content')
@include('templates.modal.modal-confirm')
<div class="card card-chart">
    <div class="card-header">
        <h4 class="card-title">Banner</h4>
        <div class="dropdown">
            <button type="button" class="btn btn-round btn-default dropdown-toggle btn-simple btn-icon no-caret" data-toggle="dropdown" aria-expanded="false">
                <i class="now-ui-icons loader_gear"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{{ route('admin.promos.banner.create') }}">Create banner</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row mb-3">
            <div class="col-12 col-md-4">
                <div class="form-group">
                    <label for="filterStatus">Filter Status</label>
                    {{ Form::select('status', $statusList, '', ['class' => 'form-control', 'id' => 'filterStatus', 'placeholder' => 'Filter Status']) }}
                </div>
            </div>
        </div>
        <table cellpadding="0" cellspacing="0" class="table table-striped table-bordered datatable dataTable" id="table" width="100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Urut</th>
                    <th>Cover</th>
                    <th>Start / End Date</th>
                    <th>Category</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@endsection

@push('pageRelatedJs')
<script>
	$(document).ready(function(){
        var filterStatusEnum = null;
		var table = $('#table').DataTable(
		{
			processing: true,
			serverSide: true,
            responsive: true,
			ajax: {
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				url: '{!! route('admin.promos.banner.ajax') !!}',
                data: function(d) { 
                    d.status_enum = filterStatusEnum;
                },
				type: 'POST'
			},
			columns: [
                { data: 'id', name: 'id', className: 'text-center' },
                { data: 'urut', name: 'urut', className: 'text-center' },
                { data: 'cover', name: 'cover', className: 'text-center', orderable: false, searchable: false, render: function (data, type, full, meta) {
                    if (!data) return '';
                    var str = '<a href="'+ data +'" target="_blank"><img id="previewImage" src="'+ data +'"/></a>';
                    return str;
                    }
                },
                { data: 'start_end_date', name: 'start_end_date', className: 'text-center' },
                { data: 'category', name: 'category', className: 'text-center' },
                { data: 'status', name: 'status', className: 'text-center' },
                { data: 'action', name: 'action', className: 'text-center', orderable: false, searchable: false  }
			]
		});
		$(table.table().container()).removeClass( 'form-inline');

        $('#filterStatus').on('change', function(e) { 
            filterStatusEnum = e.currentTarget.value; 
            table.draw(); 
        }); 
	});
</script>
@endpush