routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Webview
Route::group(['namespace' => 'Webview', 'prefix' => 'webview', 'as' => 'webview.'], function() {
	Route::get('password/reset/{token}', 'ResetPasswordController@resetPage')->name('reset.password.page');
	Route::post('password/reset', 'ResetPasswordController@reset')->name('reset.password');

	Route::get('terms-conditions', 'AboutAppController@termsConditions')->name('terms-conditions');
	Route::get('privacy-policy', 'AboutAppController@privacyPolicy')->name('privacy-policy');
	Route::get('about-us', 'AboutAppController@aboutUs')->name('about-us');
	Route::get('package-info', 'AboutAppController@packageInfo')->name('package-info');

	Route::get('/promo/{promo}', 'PromoController@detail')->name('promo-detail');
	Route::get('cara-isi-saldo', function() {
		return view('webview.cara-isi-saldo');
	});

	// Logged in
	Route::group(['middleware' => 'auth.params'], function() {
		Route::get('binary', 'BinaryController@show')->name('binary');
	});
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Guest
	Route::group(['middleware' => 'guest:web-admin', 'guard' => 'web-admin'], function() {
		Route::get('login', 'AuthController@loginPage')->name('login.page');
		Route::post('login', 'AuthController@login')->name('login');
	});

	// Logged In
	Route::group(['middleware' => 'auth:web-admin', 'guard' => 'web-admin'], function() {
	    Route::post('logout', 'AuthController@logout')->name('logout');
		Route::get('', 'DashboardController@index')->name('dashboard');
		
		// Admin
		Route::group(['prefix' => 'admins', 'as' => 'admins.'], function() {
			Route::get('/', 'AdminController@index')->name('index');
			Route::post('/', 'AdminController@ajax')->name('ajax');
			
			Route::get('/new', 'AdminController@edit')->name('create');
			Route::get('/{admin}/edit', 'AdminController@edit')->name('edit');
			Route::post('/store', 'AdminController@update')->name('store');
			Route::post('/{admin}/update', 'AdminController@update')->name('update');
			Route::delete('/{admin}/delete', 'AdminController@delete')->name('delete');
		});
		// User
		Route::group(['namespace' => 'User', 'prefix' => 'users', 'as' => 'users.'], function() {
			// User List
			Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
				Route::get('/', 'UserController@index')->name('index');
				Route::post('/', 'UserController@ajax')->name('ajax');
				Route::get('/{user}/detail', 'UserController@detail')->name('detail');
				Route::get('/new', 'UserController@edit')->name('create');
				Route::get('/{user}/edit', 'UserController@edit')->name('edit');
				Route::post('/store', 'UserController@update')->name('store');
				Route::post('/{user}/update', 'UserController@update')->name('update');
				Route::delete('/{user}/delete', 'UserController@delete')->name('delete');
			});
			// User upgrade request
			Route::group(['prefix' => 'upgrade-request', 'as' => 'upgrade-request.'], function() {
				Route::get('/', 'UpgradeRequestController@index')->name('index');
				Route::post('/', 'UpgradeRequestController@ajax')->name('ajax');
				
				Route::get('/{upgradeRequest}/edit', 'UpgradeRequestController@edit')->name('edit');
				Route::post('/{upgradeRequest}/approve', 'UpgradeRequestController@approve')->name('approve');
				Route::post('/{upgradeRequest}/decline', 'UpgradeRequestController@decline')->name('decline');
				Route::delete('/{upgradeRequest}/delete', 'UpgradeRequestController@delete')->name('delete');
			});
			// User verify identity
			Route::group(['prefix' => 'verify-identity', 'as' => 'verify-identity.'], function() {
				Route::get('/', 'VerifyIdentityController@index')->name('index');
				Route::post('/', 'VerifyIdentityController@ajax')->name('ajax');
				
				Route::get('/{user}/edit', 'VerifyIdentityController@edit')->name('edit');
				Route::post('/{user}/approve', 'VerifyIdentityController@approve')->name('approve');
				Route::post('/{user}/decline', 'VerifyIdentityController@decline')->name('decline');
				Route::delete('/{user}/delete', 'VerifyIdentityController@delete')->name('delete');
			});
			// Route::group(['prefix' => 'pair', 'as' => 'pair.'], function() {
			// 	Route::get('/', 'PairController@index')->name('index');
			// 	Route::post('/', 'PairController@ajax')->name('ajax');
				
			// 	Route::post('/store', 'PairController@update')->name('store');
			// 	Route::post('/{pair}/claim', 'PairController@claim')->name('claim');
			// 	Route::delete('/{pair}/delete', 'PairController@delete')->name('delete');
			// });
		});
		// Bank
		Route::group(['prefix' => 'bank', 'as' => 'bank.'], function() {
			Route::get('/', 'BankController@index')->name('index');
			Route::post('/', 'BankController@ajax')->name('ajax');
			Route::get('/new', 'BankController@edit')->name('create');
			Route::get('/{bank}/edit', 'BankController@edit')->name('edit');
			Route::post('/store', 'BankController@update')->name('store');
			Route::post('/{bank}/update', 'BankController@update')->name('update');
			Route::delete('/{bank}/delete', 'BankController@delete')->name('delete');
		});
		// Bank Account
		Route::group(['prefix' => 'bank-account', 'as' => 'bank-account.'], function() {
			Route::get('/', 'BankAccountController@index')->name('index');
			Route::post('/', 'BankAccountController@ajax')->name('ajax');
			Route::get('/new', 'BankAccountController@edit')->name('create');
			Route::get('/{bankAccount}/edit', 'BankAccountController@edit')->name('edit');
			Route::post('/store', 'BankAccountController@update')->name('store');
			Route::post('/{bankAccount}/update', 'BankAccountController@update')->name('update');
			Route::delete('/{bankAccount}/delete', 'BankAccountController@delete')->name('delete');
		});
		// Promo
		Route::group(['namespace' => 'Promo', 'prefix' => 'promos', 'as' => 'promos.'], function() {
			// Voucher
			// Route::group(['prefix' => 'voucher', 'as' => 'voucher.'], function(){
			// 	Route::get('/', 'VoucherController@index')->name('index');
			// 	Route::get('/new', 'VoucherController@edit')->name('create');
			// 	Route::get('/{promo}/push-notif', 'VoucherController@pushNotif')->name('push-notif');
			// 	Route::get('/{promo}/authorize', 'VoucherController@authorizeVoucher')->name('authorize');
			// 	Route::get('/{promo}/deauthorize', 'VoucherController@deauthorizeVoucher')->name('deauthorize');
			// 	Route::post('/store', 'VoucherController@update')->name('store');
			// 	Route::get('/{promo}/edit', 'VoucherController@edit')->name('edit');
			// 	Route::post('/{promo}/save', 'VoucherController@update')->name('update');
			// 	Route::post('/{promo}/push-notif', 'VoucherController@postPushNotif')->name('post-push-notif');
			// 	Route::post('/list', 'VoucherController@ajax')->name('ajax');
			// 	Route::delete('/{promo}/delete', 'VoucherController@delete')->name('delete');
			// });
			// Banner
			Route::group(['prefix' => 'banner', 'as' => 'banner.'], function(){
				Route::get('/', 'BannerController@index')->name('index');
				Route::get('/new', 'BannerController@edit')->name('create');
				Route::post('/store', 'BannerController@update')->name('store');
				// Route::get('/{promo}/push-notif', 'BannerController@pushNotif')->name('push-notif');
				Route::get('/{promo}/edit', 'BannerController@edit')->name('edit');
				Route::post('/{promo}/save', 'BannerController@update')->name('update');
				// Route::post('/{promo}/push-notif', 'BannerController@postPushNotif')->name('post-push-notif');
				Route::post('/list', 'BannerController@ajax')->name('ajax');
				Route::delete('/{promo}/delete', 'BannerController@deletePromo')->name('delete');
			});
		});
		// Categories
		Route::group(['prefix' => 'categories', 'as' => 'categories.'], function() {
			Route::get('/', 'CategoryController@index')->name('index');
			Route::post('/', 'CategoryController@ajax')->name('ajax');
			Route::get('/new', 'CategoryController@edit')->name('create');
			Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
			Route::post('/store', 'CategoryController@update')->name('store');
			Route::post('/{category}/update', 'CategoryController@update')->name('update');
			Route::delete('/{category}/delete', 'CategoryController@delete')->name('delete');
		});
		// Products
		Route::group(['prefix' => 'products', 'as' => 'products.'], function() {
			Route::get('/', 'ProductController@index')->name('index');
			Route::post('/', 'ProductController@ajax')->name('ajax');
			Route::get('/new', 'ProductController@edit')->name('create');
			Route::get('/{product}/edit', 'ProductController@edit')->name('edit');
			Route::post('/store', 'ProductController@update')->name('store');
			Route::post('/{product}/update', 'ProductController@update')->name('update');
			Route::delete('/{product}/delete', 'ProductController@delete')->name('delete');
		});
		// Payment
		Route::group(['prefix' => 'payments', 'as' => 'payments.'], function() {
			Route::get('/', 'PaymentController@index')->name('index');
			Route::post('/', 'PaymentController@ajax')->name('ajax');
			Route::get('/external', 'PaymentController@external')->name('external');
			Route::post('/external', 'PaymentController@externalAjax')->name('external-ajax');
			Route::get('/new', 'PaymentController@edit')->name('create');
			Route::get('/{payment}/edit', 'PaymentController@edit')->name('edit');
			Route::post('/store', 'PaymentController@update')->name('store');
			Route::post('/{payment}/update', 'PaymentController@update')->name('update');

app/Http/Controllers/Admin/User/PairController.php
<?php

namespace App\Http\Controllers\Admin\User;
 
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use Exception;
use App\Models\Pair;
use App\Models\User;
use App\Helpers\Managers\PairManager;
use App\Helpers\Enums\PairClaim;
use App\Helpers\Enums\PackageType;
use DataTables;
use Illuminate\Support\Collection;
use Carbon\Carbon;

class PairController extends Controller
{
    public function index(Request $request)
    {
        $statusList = PairClaim::getArray();
        $packageList = PackageType::getArray();

        return view('admin.users.pair.index')
            ->with('statusList', $statusList)
            ->with('packageList', $packageList);
    }

    public function ajax(Request $request)
    {
        $data = Pair::whereNull('claimed_at')->with('leaderUser', 'leftBinaryUser', 'rightBinaryUser')->select('pairs.*');
    	return DataTables::eloquent($data)
            ->filter(function($model) use ($request) {
                if ($request->has('dates') && $request->dates !== null) {
                    $date1 = $request->dates[0];
                    $date2 = new Carbon($request->dates[1].'23:59:59');
                    
                    $model->whereBetween('created_at', [$date1, $date2]);
                }
                if ($request->has('status_enum') && $request->status_enum !== null) {
                    $model->where('is_leader_claimed', $request->status_enum);
                }
                if ($request->has('package_enum') && $request->package_enum !== null) {
                    $model->where('leader_package_type', $request->package_enum);
                }
            }, true)
            ->addColumn('action', function ($model) {
                $str = '<div class="btn-group btn-group-circle">';
                if (!$model->is_leader_claimed) $str .= '<a data-url="'. route('admin.users.pair.claim', ['pair' => $model->id]) .'" class="action" data-toggle="modal" data-target="#modalConfirm" data-table-name="#table" data-method="POST" data-message="Are you sure to <b>CLAIM</b> this pair?"><span class="fas fa-check"></span></a>';
                $str .= '<a data-url="'. route('admin.users.pair.delete', ['pair' => $model->id]) .'" class="action" data-toggle="modal" data-target="#modalConfirm" data-table-name="#table"><span class="far fa-trash-alt"></span></a>';
                $str .= '</div>';
                return $str;
            })
            ->addColumn('package', function ($model) {
                return PackageType::getString($model->leader_package_type);
            })
            ->addColumn('claimed', function ($model) {
                $str = PairClaim::getString($model->is_leader_claimed);
                // if ($model->is_leader_claimed) $str .= ' ('.$model->claimed_at->format('Y-m-d').')';
                return $str;
            })
            ->addColumn('total', function ($model) {
                return number_format(PackageType::getPairingBonus($model->leader_package_type),0,',','.');
            })
            ->editColumn('created_at', function ($model) {
                return $model->created_at->format('j-M-Y');
            })
            ->make(true);
    }

    public function update(Request $request, Pair $pair)
    {
        $validatedData = $request->validate([
            'leader_user_id' => 'required|numeric',
            'left_binary_user_id' => 'required|numeric',
            'right_binary_user_id' => 'required|numeric'
        ]);

        try {
            DB::beginTransaction();
            $pairManager = new PairManager;
            $updatedPair = $pairManager->update($pair, $request->all());
            DB::commit();
            return redirect()->route('admin.users.pair.index')->with('success', 'Pair successfully created');
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return redirect()->back()->with('error', $errorMessage);
        }
    }

    public function claim(Request $request, Pair $pair)
    {
        try {
            DB::beginTransaction();
            $pairManager = new PairManager;
            $updatedPair = $pairManager->claim($request, $pair);
            DB::commit();
            return response()->json(['message' => 'Pair successfully Claimed'], 200);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return response()->json(['message' => $errorMessage], 500);
        }
    }

    public function delete(Request $request, Pair $pair)
    {
        try {
            DB::beginTransaction();
            $pairManager = new PairManager($pair);
            $updatedPair = $pairManager->delete($pair);
            DB::commit();
            return response()->json(['message' => 'Pair successfully Deleted'], 200);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return response()->json(['message' => $errorMessage], 500);
        }
    }
}

resources/views/admin/users/verify-identity/form.blade.php
@extends('templates.admin.master')

@section('title')
    User Verify Identity @parent
@endsection
@section('groupName', 'Users')

@section('content')
{{-- <div class="card">
    <div class="card-header">
        <h4 class="card-title">Binary Tree</h4>
    </div>
    <div class="card-body">
        @if (count($binaries) > 0)
        <div class="tree-container" id="tree-container"></div>
        @else
        <div class="mb-5">
            <p class="fs-7 f-light text-grey mb-0 text-center">No binary found</p>
        </div>
        @endif
    </div>
</div> --}}
{!! Form::model($user, ['url' => '/', 'method' => 'post', 'class' => 'form-horizontal']) !!}
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Verify Identity Detail</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <label for="id" class="col-2 col-form-label">Id</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('id', $user->id, ['class' => 'form-control', 'id' => 'id', 'disabled', 'placeholder' => 'Id']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="firstName" class="col-2 col-form-label">First Name</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('first_name', old('first_name'), ['class' => 'form-control', 'id' => 'firstName', 'placeholder' => 'First Name']) }}
                        @if($errors->has('first_name'))
                        <p class="status-text">{{ $errors->first('first_name') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="lastName" class="col-2 col-form-label">Last Name</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('last_name', old('last_name'), ['class' => 'form-control', 'id' => 'lastName', 'placeholder' => 'Last Name']) }}
                        @if($errors->has('last_name'))
                        <p class="status-text">{{ $errors->first('last_name') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="email" class="col-2 col-form-label">Email</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('email', $user->email, ['class' => 'form-control', 'id' => 'email', 'disabled', 'placeholder' => 'Email']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="phoneNumber" class="col-2 col-form-label">Phone Number</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('phone_number', $user->phone_number, ['class' => 'form-control', 'id' => 'phoneNumber', 'disabled', 'placeholder' => 'Phone Number']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="identificationNumber" class="col-2 col-form-label">Identification Number</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('identification_number', old('identification_number'), ['class' => 'form-control', 'id' => 'identificationNumber', 'placeholder' => 'Identification Number', 'required']) }}
                        @if($errors->has('identification_number'))
                        <p class="status-text">{{ $errors->first('identification_number') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-2 col-form-label">NRIC Image</label>
                <div class="col-10">
                    <div class="form-group">
                        <img class="" src="{{ $user->documents()->type(UserDocumentType::NRIC)->first()->attachment_url }}" alt="">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-2 col-form-label">Selfie Image</label>
                <div class="col-10">
                    <div class="form-group">
                        <img class="" src="{{ $user->documents()->type(UserDocumentType::SELFIE)->first()->attachment_url }}" alt="">
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <label for="desc" class="col-2 col-form-label">Description<br><small>(Optional)</small></label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::textarea('description', old('description'), ['class' => 'form-control', 'id' => 'desc', 'placeholder' => 'Any description before Approving / Declining']) }}
                        @if($errors->has('description'))
                        <p class="status-text">{{ $errors->first('description') }}</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            @if ($user->documents_status['nric'] == UserDocumentStatus::PENDING)
            <div class="text-center">
                <div class="d-inline-block mx-1">
                    <button type="button" data-action="{{ route('admin.users.verify-identity.decline', $user) }}" class="btn btn-round btn-danger"><i class="fas fa-times-circle"></i> Decline</button>
                </div>
                <div class="d-inline-block mx-1">
                    <button type="button" data-action="{{ route('admin.users.verify-identity.approve', $user) }}" class="btn btn-round btn-info"><i class="fas fa-check-circle"></i> Approve</button>
                </div>
            </div>
            @else
            <div class="text-center">
                <div class="d-inline-block mx-1">
                    @if ($user->documents_status['nric'] == UserDocumentStatus::VERIFIED)
                    <button type="button" class="btn btn-round btn-info"><i class="fas fa-check-circle"></i> Approved</button>
                    @elseif ($user->documents_status['nric'] == UserDocumentStatus::DECLINED)
                    <button type="button" class="btn btn-round btn-danger"><i class="fas fa-times-circle"></i> Declined</button>
                    @else
                    @endif
                </div>
            </div>
            @endif
        </div>
    </div>
{!! Form::close() !!}
@endsection

@push('pageRelatedCss')
<!-- <link rel="stylesheet" href="{{ asset('css/Treant.css') }}" type="text/css"/> -->
@endpush

@push('pageRelatedJs')
{{-- <script src="{{ asset('js/raphael.js') }}"></script>
<script src="{{ asset('js/Treant.js') }}"></script>
<script type="text/javascript">
    var binaries = {!! json_encode($binaries) !!};
	
	var config = {
		container: "#tree-container",
		connectors: {
			type: 'bCurve',
			style: {
				stroke: '#000',
				'stroke-width': 2,
				'stroke-opacity': '.7',
			}
		},
		siblingSeparation: 15,
		rootOrientation: 'NORTH',
		node: {
			collapsable: true,
		}
	};

    var nodes = [];

    	binaries.forEach(function(binary, i) {
		if (binary.level == 0) {
            let packageClass = '';
            if (binary.type == 0) {
                packageClass = 'free';
            } else if (binary.type == 1) {
                packageClass = 'silver';
            } else if (binary.type == 2) {
                packageClass = 'gold';
            } else if (binary.type == 3) {
                packageClass = 'platinum';
            }

			nodes.push({
				id: binary.id,
				text: {
					name: binary.fullname,
					desc: 'ID: ' + binary.user_id
				},
                HTMLclass: packageClass,
			});
		} else {
			var parent = nodes.find(function(element) {
				return element.id == binary.leader_binary_id;
			});
            let packageClass = '';
            if (binary.type == 0) {
                packageClass = 'free';
            } else if (binary.type == 1) {
                packageClass = 'silver';
            } else if (binary.type == 2) {
                packageClass = 'gold';
            } else if (binary.type == 3) {
                packageClass = 'platinum';
            }

			nodes.push({
				parent: parent,
				id: binary.id,
				text: {
					name: binary.fullname,
					desc: 'ID: ' + binary.user_id
				},
                HTMLclass: packageClass,
			});
		}
	});

	var temp = [
		config
	];

	var simple_chart_config = temp.concat(nodes);
	var my_chart = new Treant(simple_chart_config);
</script> --}}
<script>
$(document).ready(function(){
    $('button[data-action]').on('click', function() {
        let form = $('form');
        form.attr('action', $(this).data('action'));

        form.submit();
    });
    
    // $('#tree-container').perfectScrollbar();
});
</script>
@endpush

resources/views/admin/users/verify-identity/index.blade.php
@extends('templates.admin.master')
@extends('templates.datatables.datatables')

@section('title')
    User Verify Identity @parent
@endsection
@section('groupName', 'Users')

@section('content')
@include('templates.modal.modal-confirm')
<div class="card card-chart">
    <div class="card-header">
        <h4 class="card-title">User Verify Identity</h4>
    </div>
    <div class="card-body">
        <table cellpadding="0" cellspacing="0" class="table table-striped table-bordered datatable dataTable" id="table" width="100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th class="d-none">First Name</th>
                    <th class="d-none">Last Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@endsection

@push('pageRelatedJs')
<script>
	$(document).ready(function(){
		var table = $('#table').DataTable(
		{
			processing: true,
			serverSide: true,
            responsive: true,
			ajax: {
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				url: '{!! route('admin.users.verify-identity.ajax') !!}',
				type: 'POST'
			},
			columns: [
                { data: 'id', name: 'id', className: 'text-center' },
                
                { data: 'fullname', className: 'text-center', sortable: false, searchable: false },
                { data: 'first_name', name: 'first_name', visible: false },
                { data: 'last_name', name: 'last_name', visible: false },
                
                { data: 'email', name: 'email', className: 'text-center' },
                { data: 'phone_number', name: 'phone_number', className: 'text-center' },
                { data: 'action', name: 'action', className: 'text-center', sortable: false },
			]
		});
		$(table.table().container()).removeClass('form-inline');
	});
</script>
@endpush