routes/web.php
			Route::post('/store', 'AdminController@update')->name('store');
			Route::post('/{admin}/update', 'AdminController@update')->name('update');
			Route::delete('/{admin}/delete', 'AdminController@delete')->name('delete');
		});
		// User
		Route::group(['namespace' => 'User', 'prefix' => 'users', 'as' => 'users.'], function() {
			// User List
			Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
				Route::get('/', 'UserController@index')->name('index');
				Route::post('/', 'UserController@ajax')->name('ajax');
				Route::get('/{user}/detail', 'UserController@detail')->name('detail');
				Route::get('/new', 'UserController@edit')->name('create');
				Route::get('/{user}/edit', 'UserController@edit')->name('edit');
				Route::post('/store', 'UserController@update')->name('store');
				Route::post('/{user}/update', 'UserController@update')->name('update');
				Route::delete('/{user}/delete', 'UserController@delete')->name('delete');
			});
			// User upgrade request
			Route::group(['prefix' => 'upgrade-request', 'as' => 'upgrade-request.'], function() {
				Route::get('/', 'UpgradeRequestController@index')->name('index');
				Route::post('/', 'UpgradeRequestController@ajax')->name('ajax');
				
				Route::get('/{upgradeRequest}/edit', 'UpgradeRequestController@edit')->name('edit');
				Route::post('/{upgradeRequest}/approve', 'UpgradeRequestController@approve')->name('approve');
				Route::post('/{upgradeRequest}/decline', 'UpgradeRequestController@decline')->name('decline');
				Route::delete('/{upgradeRequest}/delete', 'UpgradeRequestController@delete')->name('delete');
			});
			// User verify identity
			Route::group(['prefix' => 'verify-identity', 'as' => 'verify-identity.'], function() {
				Route::get('/', 'VerifyIdentityController@index')->name('index');
				Route::post('/', 'VerifyIdentityController@ajax')->name('ajax');
				
				Route::get('/{user}/edit', 'VerifyIdentityController@edit')->name('edit');
				Route::post('/{user}/approve', 'VerifyIdentityController@approve')->name('approve');
				Route::post('/{user}/decline', 'VerifyIdentityController@decline')->name('decline');
				Route::delete('/{user}/delete', 'VerifyIdentityController@delete')->name('delete');
			});
			// Route::group(['prefix' => 'pair', 'as' => 'pair.'], function() {
			// 	Route::get('/', 'PairController@index')->name('index');
			// 	Route::post('/', 'PairController@ajax')->name('ajax');
				
			// 	Route::post('/store', 'PairController@update')->name('store');
			// 	Route::post('/{pair}/claim', 'PairController@claim')->name('claim');
			// 	Route::delete('/{pair}/delete', 'PairController@delete')->name('delete');
			// });
		});
		// Bank
		Route::group(['prefix' => 'bank', 'as' => 'bank.'], function() {
			Route::get('/', 'BankController@index')->name('index');
			Route::post('/', 'BankController@ajax')->name('ajax');
			Route::get('/new', 'BankController@edit')->name('create');
			Route::get('/{bank}/edit', 'BankController@edit')->name('edit');
			Route::post('/store', 'BankController@update')->name('store');
			Route::post('/{bank}/update', 'BankController@update')->name('update');
			Route::delete('/{bank}/delete', 'BankController@delete')->name('delete');
		});
		// Bank Account
		Route::group(['prefix' => 'bank-account', 'as' => 'bank-account.'], function() {
			Route::get('/', 'BankAccountController@index')->name('index');
			Route::post('/', 'BankAccountController@ajax')->name('ajax');
			Route::get('/new', 'BankAccountController@edit')->name('create');
			Route::get('/{bankAccount}/edit', 'BankAccountController@edit')->name('edit');
			Route::post('/store', 'BankAccountController@update')->name('store');
			Route::post('/{bankAccount}/update', 'BankAccountController@update')->name('update');
			Route::delete('/{bankAccount}/delete', 'BankAccountController@delete')->name('delete');
		});
		// Promo
		Route::group(['namespace' => 'Promo', 'prefix' => 'promos', 'as' => 'promos.'], function() {
			// Voucher
			// Route::group(['prefix' => 'voucher', 'as' => 'voucher.'], function(){
			// 	Route::get('/', 'VoucherController@index')->name('index');
			// 	Route::get('/new', 'VoucherController@edit')->name('create');
			// 	Route::get('/{promo}/push-notif', 'VoucherController@pushNotif')->name('push-notif');
			// 	Route::get('/{promo}/authorize', 'VoucherController@authorizeVoucher')->name('authorize');
			// 	Route::get('/{promo}/deauthorize', 'VoucherController@deauthorizeVoucher')->name('deauthorize');
			// 	Route::post('/store', 'VoucherController@update')->name('store');
			// 	Route::get('/{promo}/edit', 'VoucherController@edit')->name('edit');
			// 	Route::post('/{promo}/save', 'VoucherController@update')->name('update');
			// 	Route::post('/{promo}/push-notif', 'VoucherController@postPushNotif')->name('post-push-notif');
			// 	Route::post('/list', 'VoucherController@ajax')->name('ajax');
			// 	Route::delete('/{promo}/delete', 'VoucherController@delete')->name('delete');
			// });
			// Banner
			Route::group(['prefix' => 'banner', 'as' => 'banner.'], function(){
				Route::get('/', 'BannerController@index')->name('index');
				Route::get('/new', 'BannerController@edit')->name('create');
				Route::post('/store', 'BannerController@update')->name('store');
				// Route::get('/{promo}/push-notif', 'BannerController@pushNotif')->name('push-notif');
				Route::get('/{promo}/edit', 'BannerController@edit')->name('edit');
				Route::post('/{promo}/save', 'BannerController@update')->name('update');
				// Route::post('/{promo}/push-notif', 'BannerController@postPushNotif')->name('post-push-notif');
				Route::post('/list', 'BannerController@ajax')->name('ajax');
				Route::delete('/{promo}/delete', 'BannerController@deletePromo')->name('delete');
			});
		});
		// Categories
		Route::group(['prefix' => 'categories', 'as' => 'categories.'], function() {
			Route::get('/', 'CategoryController@index')->name('index');
			Route::post('/', 'CategoryController@ajax')->name('ajax');
			Route::get('/new', 'CategoryController@edit')->name('create');
			Route::get('/{category}/edit', 'CategoryController@edit')->name('edit');
			Route::post('/store', 'CategoryController@update')->name('store');
			Route::post('/{category}/update', 'CategoryController@update')->name('update');
			Route::delete('/{category}/delete', 'CategoryController@delete')->name('delete');
		});
		// Products
		Route::group(['prefix' => 'products', 'as' => 'products.'], function() {
			Route::get('/', 'ProductController@index')->name('index');
			Route::post('/', 'ProductController@ajax')->name('ajax');
			Route::get('/new', 'ProductController@edit')->name('create');
			Route::get('/{product}/edit', 'ProductController@edit')->name('edit');
			Route::post('/store', 'ProductController@update')->name('store');
			Route::post('/{product}/update', 'ProductController@update')->name('update');
			Route::delete('/{product}/delete', 'ProductController@delete')->name('delete');
		});
		// Payment
		Route::group(['prefix' => 'payments', 'as' => 'payments.'], function() {
			Route::get('/', 'PaymentController@index')->name('index');
			Route::post('/', 'PaymentController@ajax')->name('ajax');
			Route::get('/external', 'PaymentController@external')->name('external');
			Route::post('/external', 'PaymentController@externalAjax')->name('external-ajax');
			Route::get('/new', 'PaymentController@edit')->name('create');
			Route::get('/{payment}/edit', 'PaymentController@edit')->name('edit');
			Route::post('/store', 'PaymentController@update')->name('store');
			Route::post('/{payment}/update', 'PaymentController@update')->name('update');
			Route::delete('/{payment}/delete', 'PaymentController@delete')->name('delete');
		});
		// Top Up
		Route::group(['prefix' => 'top-up', 'as' => 'top-up.'], function() {
			Route::get('/', 'TopUpController@index')->name('index');
			Route::post('/', 'TopUpController@ajax')->name('ajax');
			Route::get('/new', 'TopUpController@edit')->name('create');
			Route::get('/{order}/edit', 'TopUpController@edit')->name('edit');
			Route::post('/store', 'TopUpController@store')->name('store');
			Route::get('/history', 'TopUpController@history')->name('history');
			Route::post('/history', 'TopUpController@historyAjax')->name('history-ajax');
			Route::get('/{order}/history', 'TopUpController@historyView')->name('history-view');
			Route::get('/{order}/confirmation', 'TopUpController@confirmation')->name('confirmation');
			Route::post('/{order}/update', 'TopUpController@update')->name('update');
			Route::post('/{order}/approve', 'TopUpController@approve')->name('approve');
			Route::post('/{order}/recheck', 'TopUpController@recheck')->name('recheck');
			Route::post('/{order}/decline', 'TopUpController@decline')->name('decline');
			Route::get('/{order}/print/{size}', 'TopUpController@print')->name('print');
		});
		// AppConfig
		Route::group(['prefix' => 'config', 'as' => 'config.'], function() {
			Route::get('/', 'AppConfigController@index')->name('index');
			Route::post('/', 'AppConfigController@ajax')->name('ajax');
			Route::get('/new', 'AppConfigController@edit')->name('create');
			Route::get('/{appConfig}/edit', 'AppConfigController@edit')->name('edit');
			Route::post('/store', 'AppConfigController@update')->name('store');
			Route::post('/{appConfig}/update', 'AppConfigController@update')->name('update');
			Route::delete('/{appConfig}/delete', 'AppConfigController@delete')->name('delete');
		});
		// Order
		Route::group(['prefix' => 'order', 'as' => 'order.'], function() {
			Route::get('/', 'OrderController@index')->name('index');
			Route::post('/', 'OrderController@ajax')->name('ajax');
			Route::get('/{order}/detail', 'OrderController@detail')->name('detail');
			Route::get('/{order}/set-status/{status}', 'OrderController@setStatus')->name('set-status');
			// Route::post('/{order}/update', 'OrderController@update')->name('update');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Transaction;
use App\Models\BankAccount;
use App\Enums\OrderStatus;
use App\Enums\OrderType;
use DB;
use Carbon\Carbon;

class Order extends Model
{
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'type', 'status', 'transaction_id', 'referable_type', 'referable_id', 'ownable_type', 'ownable_id', 'expired_at', 'review_id', 'options'
    ];

    //Type -> Top Up(0) | Withdraw(1)
    //Status -> Pending(0) | Accepted(1) | Expired(2) | Cancelled(3) | Declined(4)

    protected $appends = [
        'virtual', 'total', 'status_string'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['deleted_at', 'updated_at'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'options' => 'object'
    ];

    protected $dates = ['expired_at', 'deleted_at'];

    public function referable()
    {
        return $this->morphTo();
    }

    public function ownable()
    {
        return $this->morphTo();
    }

    public function approvable()
    {
        $options = is_object($this->options) ? (array) $this->options : $this->options;
        $id = isset($options['approvable_id']) ? $options['approvable_id'] : null;
        if (!$id) return null;

        $typeValue = isset($options['approvable_type']) ? $options['approvable_type'] : '';
        $class = Model::getActualClassNameForMorph($typeValue);
        $model = new $class();

        return $model::find($id);
    }

    public function recheckable()
    {
        $options = is_object($this->options) ? (array) $this->options : $this->options;
        $id = isset($options['recheckable_id']) ? $options['recheckable_id'] : null;
        if (!$id) return null;

        $typeValue = isset($options['recheckable_type']) ? $options['recheckable_type'] : '';
        $class = Model::getActualClassNameForMorph($typeValue);
        $model = new $class();

        return $model::find($id);
    }

    public function orderDetails()
    {
        return $this->hasMany('App\Models\OrderDetail');
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    public function histories()
    {
        return $this->morphMany('App\Models\History', 'historiable');
    }

    public function scopeType($query, $type)
    {
        if (is_array($type)) {
            return $query->whereIn('type', $type);
        } else {
            return $query->where('type', $type);
        }
    }

    public function scopeStatus($query, $status)
    {
        if (is_array($status)) {
            return $query->whereIn('status', $status);
        } else {
            return $query->where('status', $status);
        }
    }

    public function scopeActive($query)
    {
        $activeStatus = OrderStatus::getActiveList();
        return $query->whereIn('status', $activeStatus);
    }

    public function scopeInactive($query)
    {
        $activeStatus = OrderStatus::getActiveList();
        return $query->whereNotIn('status', $activeStatus);
    }

    public function scopeComplete($query)
    {
        return $query->where('status', OrderStatus::COMPLETED);
    }

    public function isActive()
    {
        $activeStatus = OrderStatus::getActiveList();
        return in_array($this->status, $activeStatus);
    }

    public function ownedBy($user)
    {
        if (!$this->ownable) return false;
        $className = get_class($this->ownable);
        if ($user instanceof $className) {
            return $user->id == $this->ownable->id;
        }
        return false;
    }

    public function getVirtualAttribute($value)
    {
        $options = $this->options;
        if (isset($options->dest_bank_account_id)) {
            $bankAccount = BankAccount::find($options->dest_bank_account_id);
            if ($bankAccount) $bankAccount->load('bank');
            $options->dest_bank_account = $bankAccount;
        }
        if (isset($options->bank_account_id)) {
            $bankAccount = BankAccount::find($options->bank_account_id);
            if ($bankAccount) $bankAccount->load('bank');
            $options->bank_account = $bankAccount;
        }
        return $options;
    }

    public function getTotalAttribute($value)
    {
        $result = DB::table('order_details')->where('order_id', $this->id)->selectRaw('SUM(total - discount) as sub_total, order_id')->groupBy('order_id')->first();

        return $result ? $result->sub_total : 0;
    }

    public function getTotalDiscountAttribute($value)
    {
        $result = $this->orderDetails->sum('discount');
        
        return $result;
    }

    public function getTotalBeforeDiscountAttribute($value)
    {
        $result = $this->orderDetails->sum('total');
        
        return $result;
    }

    public function getStatusStringAttribute($value)
    {
        return OrderStatus::getString($this->status);
    }

    public function history($status = null)
    {
        $query = $this->histories();
        $query->latest();
        if ($status) $query->where('status', $status);
        $history = $query->first();

        return $history;
    }

    public function scopeRecent($query)
    {
        return $query->where('created_at', '>', Carbon::now()->subDays(30));
    }
}

resources/views/admin/top-up/confirmation.blade.php
@extends('templates.admin.master')

@section('title', 'Top Up Confirmation')
@section('groupName', 'Top Up')

@section('content')
@include('templates.modal.modal-decline', ['choices' => $choices])
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Top Up Confirmation</h3>
    </div>
    <div class="card-body">
        <form class="form-horizontal">
            <div class="row">
                <label for="referenceNumber" class="col-2 col-form-label">Reference Number</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('reference_number', $order->reference_number, ['class' => 'form-control', 'id' => 'referenceNumber', 'readonly', 'placeholder' => 'Reference Number']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="fullname" class="col-2 col-form-label">Request By</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('fullname', $ownable->fullname, ['class' => 'form-control', 'id' => 'fullname', 'readonly', 'placeholder' => 'Fullname']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="amount" class="col-2 col-form-label">Amount</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('amount', GlobalHelper::toCurrency($order->total_before_discount), ['class' => 'form-control', 'id' => 'amount', 'readonly', 'placeholder' => 'Amount']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="discount" class="col-2 col-form-label">Discount</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('discount', GlobalHelper::toCurrency($order->total_discount), ['class' => 'form-control', 'id' => 'discount', 'readonly', 'placeholder' => 'Discount']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="total" class="col-2 col-form-label">Total</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('total', GlobalHelper::toCurrency($order->total), ['class' => 'form-control', 'id' => 'total', 'readonly', 'placeholder' => 'Total']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="dateTime" class="col-2 col-form-label">Date / Time</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('date_time', $order->created_at->setTimezone('Asia/Jakarta')->format('d-M-y H:i'), ['class' => 'form-control', 'id' => 'dateTime', 'readonly', 'placeholder' => 'Date / Time']) }}
                    </div>
                </div>
            </div>
            @if (isset($order->virtual->bank_account))
                <div class="row">
                    <label class="col-2 col-form-label">Bank</label>
                    <div class="col-10">
                        <div class="form-group">
                            {{ Form::text('', $order->virtual->bank_account ? $order->virtual->bank_account->bank->name : '', ['class' => 'form-control', 'disabled']) }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-2 col-form-label">Account Name</label>
                    <div class="col-10">
                        <div class="form-group">
                            {{ Form::text('', $order->virtual->bank_account ? $order->virtual->bank_account->account_name : '', ['class' => 'form-control', 'disabled']) }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-2 col-form-label">Account No</label>
                    <div class="col-10">
                        <div class="form-group">
                            {{ Form::text('', $order->virtual->bank_account ? $order->virtual->bank_account->account_no : '', ['class' => 'form-control', 'disabled']) }}
                        </div>
                    </div>
                </div>
            @endif
            <hr>
            <h4 class="card-title mt-2 mb-4">Destination Bank Account</h4>
            <div class="row">
                <label class="col-2 col-form-label">Bank</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('', $destBankAccount ? $destBankAccount->bank->name : '', ['class' => 'form-control', 'disabled']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-2 col-form-label">Account Name</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('', $destBankAccount ? $destBankAccount->account_name : '', ['class' => 'form-control', 'disabled']) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-2 col-form-label">Account No</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('', $destBankAccount ? $destBankAccount->account_no : '', ['class' => 'form-control', 'disabled']) }}
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="card-footer">
        @if ($order->isActive())
        <div class="text-center">
            <div class="d-inline-block mx-1">
                <button type="button" class="btn btn-round btn-danger" data-url="{{ route('admin.top-up.decline', ['order' => $order]) }}" data-toggle="modal" data-target="#modalDecline"><i class="fas fa-times-circle"></i> Decline</button>
            </div>
            <div class="d-inline-block mx-1">
                {!! Form::open(['route' => ['admin.top-up.approve', $order], 'method' => 'post']) !!}
                    <button type="submit" class="btn btn-round btn-info"><i class="fas fa-check-circle"></i> Approve</button>
                {!! Form::close() !!}
            </div>
        </div>
        @else
        <div class="text-center">
            <div class="d-inline-block mx-1">
                <button type="button" class="btn btn-round btn-info">{{ OrderStatus::getString($order->status) }}</button>
            </div>
        </div>
        @endif
    </div>
</div>
@endsection

resources/views/admin/top-up/form.blade.php
@extends('layouts.backend.dashboard')
@extends('layouts.backend.side_bar')

@section('title', '| Top Up')

@section('bc-item')
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.index') }}">
        <i class="fas fa-home"></i><span>Home</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{{ route('admin.top-up.index') }}">
        <i class="fas fa-chevron-circle-down"></i><span>Top-Up</span>
    </a>
</li>
<li class="breadcrumb-item active"><i class="fas fa-plus"></i><span>Confirmation Top-Up</span></li>
@endsection

@section('content')
@if($order->id)
{!! Form::model($order, ['url' => route('admin.top-up.update', ['order' => $order]),'method' => 'POST', 'enctype'=>'multipart/form-data']) !!}
@else
{!! Form::open(['url' => route('admin.top-up.store'),'method' => 'POST', 'enctype'=>'multipart/form-data']) !!}
@endif

<div class="page-content-wrapper">
    <div class="page-content d-flex flex-column">
        @include('includes.session_message')
        <div class="squared">
            <div class="squared-title d-flex align-items-center">
                <div class="actions ml-1 mr-3">
                    <a href="{{ route('admin.top-up.index') }}" title="Back" data-toggle="tooltip" data-placement="right" class="btn btn-circle btn-icon-only">
                        <span class="entypo-back"></span>
                    </a>
                </div>
                <div class="caption">
                    {{ $order->id ? 'Edit' : 'New' }} Topup
                </div>
                <div class="actions ml-auto">
                    
                </div>
            </div>
            <div class="form-group text-left">
                <p class="">Top Up To</p>
                <label class="radio" for="user">
                    {{ Form::radio('request_by_type', 'user', false, ['id' => 'user', 'class' => 'd-none']) }}
                    <div class="circle">
                        <div class="outer-circle"></div>
                        <div class="inner-circle"></div>
                        <div class="ripple-circle"></div>
                    </div>
                    <p>User</p>
                </label>
                <label class="radio" for="business">
                    {{ Form::radio('request_by_type', 'business', false, ['id' => 'business', 'class' => 'd-none']) }}
                    <div class="circle">
                        <div class="outer-circle"></div>
                        <div class="inner-circle"></div>
                        <div class="ripple-circle"></div>
                    </div>
                    <p>Business</p>
                </label>
            </div>
            <div class="form-group" id="userList">
                {{ Form::label('request_by_id_user', 'Users List') }}
                {{ Form::select('request_by_id_user', $userList, null, array('class' => 'form-control nullable', 'placeholder' => 'Please select user', 'required' => 'required')) }}
            </div>
            <div class="form-group" id="businessList">
                {{ Form::label('request_by_id_business', 'Business List') }}
                {{ Form::select('request_by_id_business', $businessList, null, array('class' => 'form-control nullable', 'placeholder' => 'Please select business', 'required' => 'required', 'disabled')) }}
            </div>
            <div class="form-group">
                {{ Form::label('amount', 'Amount') }}
                {{ Form::number('amount', old('amount'), array('class' => 'form-control', 'placeholder' => 'Amount')) }}
            </div>
            <div class="form-group">
                {{ Form::label('dest_bank_account_id', 'Destination Bank Account') }}
                {{ Form::select('dest_bank_account_id', $destBankAccounts, null, array('class' => 'form-control nullable', 'placeholder' => 'Please select one...')) }}
            </div>
            <button type="submit" class="btn btn-outline-blue"><i class="far fa-save mr-2"></i>Submit</button>
        </div>
    </div>
</div>

{{ Form::close() }}

@endsection
@push('pageRelatedJs')
<script type="text/javascript">
    $(document).ready(function(){
        var userList = $('#userList');
        var businessList = $('#businessList');
        var radio = $('input[type=radio]');
        
        radio.on('change', function() {
            if (this.value == 'business') {
                businessList.removeClass('hide').find('select').prop('disabled', false);
                userList.addClass('hide').find('select').prop('disabled', true);
            } else {
                businessList.addClass('hide').find('select').prop('disabled', true);
                userList.removeClass('hide').find('select').prop('disabled', false);
            }
        });
    });
</script>
@endpush

resources/views/admin/top-up/index.blade.php
@extends('templates.admin.master')
@extends('templates.datatables.datatables')

@section('title')
    Top Up @parent
@endsection
@section('groupName', 'Top Up')

@section('content')
@include('templates.modal.modal-confirm')
<div class="card card-chart">
    <div class="card-header">
        <h4 class="card-title">Top Up</h4>
    </div>
    <div class="card-body">
        <div class="row mb-3">
            <div class="col-12 col-md-4">
                <div class="form-group">
                    <label for="filterStatus">Filter Status</label>
                    {{ Form::select('status', $statusList, '', ['class' => 'form-control nullable', 'id' => 'filterStatus', 'placeholder' => 'Filter Status']) }}
                </div>
            </div>
        </div>
        <table cellpadding="0" cellspacing="0" class="table table-striped table-bordered datatable dataTable" id="table" width="100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Reference Number</th>
                    <th>Status</th>
                    <th>Request By</th>
                    <th>Date / Time</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
<div class="card card-chart">
    <p>Top Up Completed amount : Rp{{ number_format($floatingWallet, 2,',','.') }} </p>
</div>
@endsection

@push('pageRelatedJs')
<script>
	$(document).ready(function(){
        var filterStatusEnum = null;
		var table = $('#table').DataTable(
		{
			processing: true,
			serverSide: true,
            responsive: true,
			ajax: {
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				url: '{!! route('admin.top-up.ajax') !!}',
                data: function(d) { 
                    d.status_enum = filterStatusEnum;
                },
				type: 'POST'
			},
			columns: [
				{ data: 'id', name: 'id', className: 'text-center' },
				{ data: 'reference_number', name: 'reference_number', className: 'text-center' },
				{ data: 'status', name: 'status', className: 'text-center' },
                { data: 'created_by', name: 'created_by', className: 'text-center' },
				{ data: 'created_at', name: 'created_at', className: 'text-center' },
                { data: 'action', name: 'action', className: 'text-center', sortable: false },
			]
		});
		$(table.table().container()).removeClass( 'form-inline');

        $('#filterStatus').on('change', function(e) { 
            filterStatusEnum = e.currentTarget.value; 
            table.draw(); 
        }); 
	});
</script>
@endpush